p true.respond_to?(:&)
p false.respond_to?(:|)
p TrueClass.instance_methods.include?(:^)
p FalseClass.instance_methods.include?(:&)
p(true & 1)
p(true & nil)
p(false | "x")
p(false | nil)
p(true ^ false)
p(true ^ 1)
