puts Math::PI.round(5)
puts Math::E.round(5)
puts Math.sqrt(4)
puts Math.sqrt(2).round(5)
puts Math.log(Math::E).round(5)
puts Math.log10(100)
puts Math.sin(0)
puts Math.cos(0)
puts Math.atan2(1, 1).round(5)
