Point = Struct.new(:x, :y)
Config = Struct.new(:host, :port, keyword_init: true)

puts Struct.respond_to?(:[])
puts Struct.respond_to?(:members)
puts Struct.respond_to?(:keyword_init?)
puts Point.respond_to?(:[])
puts Point.respond_to?(:members)
puts Point.respond_to?(:keyword_init?)
puts Config.respond_to?(:keyword_init?)

puts Struct.methods.include?(:[])
puts Struct.methods.include?(:members)
puts Struct.methods.include?(:keyword_init?)
puts Point.methods.include?(:[])
puts Point.methods.include?(:members)
puts Point.methods.include?(:keyword_init?)
puts Config.methods.include?(:keyword_init?)

puts Struct.methods(false).include?(:[])
puts Struct.public_methods(false).include?(:[])
puts Struct.methods(false).include?(:members)
puts Struct.public_methods(false).include?(:members)
puts Struct.methods(false).include?(:keyword_init?)
puts Struct.public_methods(false).include?(:keyword_init?)
